version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 886436956008.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=886436956008.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:latest > imageDetail.json
artifacts:
  files:
    - imageDetail.json
