version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 886436956008.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 886436956008.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
post_build:
  commands:
    - echo Updating kubeconfig for EKS...
    - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-cluster
    - echo Deploying new image to EKS...
    - kubectl set image deployment/brain-tasks-deployment brain-tasks-container=886436956008.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest

artifacts:
  files:
    - deployment.yaml
    - service.yaml

